### ISSUE TITLE
Use new license format in published nupkg

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.ProGet#15]
See specs here:
https://github.com/NuGet/Home/wiki/Packaging-License-within-the-nupkg-(Technical-Spec)#license-expression-pack

**Comment by gep13** [comment]
This was recently done on the Cake NuPkg's here:

https://github.com/cake-build/cake/pull/2361

**Comment by skovsende** [comment]
Does this require that dotnet pack is required for packing?

**Comment by gep13** [comment]
@skovsende good question...

I don't know the answer to that 😄 

Perhaps @mholo65 or @devlead know?

**Comment by devlead** [comment]
No you can use NuGet.exe 4.9.1 or newer too.
